tests/binder: fix reference to flat_binder_object's type
A compilation error occurs when building the tests with headers of
longterm kernel 4.4:

binder_common.c:111:14: error: ‘const struct flat_binder_object’ has no member named ‘hdr’
   switch (obj->hdr.type) {
              ^
binder_common.c:125:38: error: ‘const struct flat_binder_object’ has no member named ‘hdr’
    printf("Unknown header: %u\n", obj->hdr.type);
                                      ^

It's been checked that the member "hdr" of flat_binder_object was
introduced by feba3900cabb ("binder: Split flat_binder_object") in
kernel v4.11-rc1. Fix this problem by adding kernel version check.

Signed-off-by: GONG, Ruiqi <gongruiqi1@huawei.com>