tests/binder: Adjust kernel uapi headers check for building
Following compilation errors occur when building the tests with
userspace headers exported from kernel 4.4:

binder_common.c:111:14: error: ‘const struct flat_binder_object’ has no
member named ‘hdr’
   switch (obj->hdr.type) {
              ^
client.c:58:9: error: dereferencing pointer to incomplete type
  if (obj->hdr.type != BINDER_TYPE_FD) {
         ^

It's been checked that member `hdr` of `struct flat_binder_object` and
`struct binder_fd_object` were both introduced into kernel 4.11 by the
same commit feba3900cabb ("binder: Split flat_binder_object"). Change
the check to <linux/android/binder.h> before building binder tests to
see if it contains the definition of `struct binder_fd_object`.

Signed-off-by: GONG, Ruiqi <gongruiqi1@huawei.com>
[OM: add -s to the grep command in case the file doesn't exist]
Signed-off-by: Ondrej Mosnacek <omosnace@redhat.com>